### ISSUE TITLE
uninitialized constant Fluent::TailInput (NameError)

### ISSUE THREAD

**Issue by FaKod** [k14i/fluent-plugin-glusterfs#4]
2017-07-07 07:36:46 +0000 [info]: reading config file path="/etc/td-agent/td-agent.conf"
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-glusterfs-1.0.0/lib/fluent/plugin/in_glusterfs_log.rb:5:in `<module:Fluent>': uninitialized constant Fluent::TailInput (NameError)
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-glusterfs-1.0.0/lib/fluent/plugin/in_glusterfs_log.rb:1:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/registry.rb:102:in `block in search'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/registry.rb:99:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/registry.rb:99:in `search'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/registry.rb:44:in `lookup'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/plugin.rb:146:in `new_impl'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/plugin.rb:100:in `new_input'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/root_agent.rb:268:in `add_source'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/root_agent.rb:122:in `block in configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/root_agent.rb:118:in `each'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/root_agent.rb:118:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/engine.rb:131:in `configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/engine.rb:96:in `run_configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/supervisor.rb:756:in `run_configure'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/supervisor.rb:538:in `dry_run'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/supervisor.rb:556:in `supervise'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/supervisor.rb:462:in `run_supervisor'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.14.18/bin/fluentd:5:in `<top (required)>'
	from /opt/td-agent/embedded/bin/fluentd:23:in `load'
	from /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
	from /usr/sbin/td-agent:7:in `load'
	from /usr/sbin/td-agent:7:in `<main>'

**Comment by Netbulae** [comment]
It's been a while and nobody responded, got rid of this warning by changing 

`class GlusterfsLogInput < TailInput`

into

`class GlusterfsLogInput < Fluent::Plugin::TailInput`

This plugin hasn't been updated in years and seems abandoned, we will fork it and continue development...
